#cameras.yaml
- platform: ffmpeg
  input: !secret camera_kitchen_stream_url
  name: Kitchen
  authentication: true

- platform: mjpeg
  mjpeg_url: !secret camera_dashboard_stream_url

- platform: mjpeg
  mjpeg_url: !secret camera_usb_stream_url
  name: USB
