#cameras.yaml
- platform: ffmpeg
  input: -an -i "rtsp://10.3.1.9:554/rtsp_live0"
  name: Kitchen
  authentication: true

- platform: mjpeg
  mjpeg_url: http://10.3.1.17:6080/video

- platform: mjpeg
  mjpeg_url: http://10.3.1.2:8081
  name: USB
